added Equivalent axiom to 'autosomal dominant cataract' and added sub…
monarch-initiative/mondo pull request #3372
Opened 2021-07-23 22:01 UTC by sabrinatoro

…class

Fix #2951

The following terms were inferred as children based on their subclassification to 'systemic disease with cataract': autosomal dominant Alport syndrome (MONDO:0007086), autosomal dominant rhegmatogenous retinal detachment (MONDO:0016202).

Note: I wasn't sure which 'source' to add

2021-07-28 15:35 UTC, nicolevasilevsky commented
hi - sorry I didn't review your nice [spreadsheet](https://docs.google.com/spreadsheets/d/1pF_kJodM50hTW_tV74pJZb6mKFcGoDe9C5vrWXYP5Cc/edit#gid=729586216) earlier. I like option #2 to add the superclassOf axioms, then we'll get autoclassifications. And in answer to your question on the spreadsheet, yes, we can add superclassOf axioms like that.

here is an example:
'early-onset autosomal dominant Alzheimer disease'
![image](https://user-images.githubusercontent.com/6722114/127351913-9c697429-1a28-4647-b414-276da8a533e5.png)

2021-07-28 15:59 UTC, nicolevasilevsky requested changes
per my comment on the 'conversation', could you please add subclassOf axioms instead of asserting the superclasses?
thank you!

2021-07-28 16:35 UTC, sabrinatoro commented
changes done

2021-07-29 20:24 UTC, nicolevasilevsky approved these changes

2021-07-29 20:24 UTC, merged