New organization
monarch-initiative/mondo pull request #4717
Opened 2022-04-06 19:01 UTC by sabrinatoro

@nicolevasilevsky @matentzn 
Please check this new proposed organization.
Note that it looks like we have some pages which might contain similar information, but this is future work.

2022-04-06 19:30 UTC, nicolevasilevsky approved these changes
this looks good to me, thank you!
Feel free to go ahead and merge

2022-04-06 19:48 UTC, matentzn requested changes
I am missing some more clear user facing section including the obsoletion guidelines and the new mapping docs we just wrote :)

2022-04-06 19:48 UTC, matentzn commented on mkdocs.yml
> +      - Difs: editors-guide/diffs.md
Diffs

2022-04-06 19:48 UTC, matentzn commented on mkdocs.yml
> +    - Miscelaneous:
Miscellaneous

2022-04-06 19:48 UTC, matentzn commented on mkdocs.yml
> +      - Qualtiy control tests: editors-guide/quality-control-tests.md
Quality

2022-04-06 20:07 UTC, sabrinatoro commented
@matentzn 
I resolved the typos issues (though it looks like it was sent to another PR... )
Note that I simply moved things around, so there might be more typos... 

The new document was not yet merged when I did this. I don't know how that will affect @nicolevasilevsky's PR. 

In terms of "user facing section" : I created the section "Mondo Editing (rules and practices)"
Do you mean that we need documentation for users to refer to in order to learn our workflow, how we handle obsoletion,... ? 
Maybe we need to create new documentation especially created for users? (I honestly don't know if any of the one we currently have is clearly user centric - except for the new one which is not here)

2022-04-06 20:11 UTC, merged

2022-04-07 04:10 UTC, matentzn commented
The ones that explain what the annotation properties / codes mean we use in Mondo, the one with the obsoletion contract, the mapping one anything that is for people that _use_ mondo for something, like clingen.