`mapping_set_id` corrected
monarch-initiative/mondo pull request #6194
Opened 2023-04-11 14:29 UTC by hrshdhgd

Addresses #5846

2023-04-11 14:50 UTC, matentzn requested changes
- Many `object_label` columns have disappeared from the split file
- Can we add `object_label` to the main mondo.sssom.tsv file?

2023-04-11 14:50 UTC, matentzn commented on src/ontology/metadata/mondo.sssom.config.yml
> +  mapping_set_id: "http://purl.obolibrary.org/obo/mondo/mappings/mondo.sssom.tsv" # Apparently this is the one that matters.
Is this needed when `sssom annotate`?

2023-04-11 15:01 UTC, hrshdhgd commented on src/ontology/metadata/mondo.sssom.config.yml
> +  mapping_set_id: "http://purl.obolibrary.org/obo/mondo/mappings/mondo.sssom.tsv" # Apparently this is the one that matters.
not really. I'll change it.

2023-04-12 21:04 UTC, hrshdhgd commented
I think the latest run fixed the missing `object_label` issue. I had to run `make mondo-ingest.owl` and `semsql make tmp/mondo-ingest.db -P config/prefixes.csv` again before `make mappings`.

2023-04-13 10:42 UTC, matentzn reviewed
This looks great! Almost there! Can you 

1. Make sure that we don't have to run anything manually? Maybe update https://github.com/monarch-initiative/mondo/blob/550263a2d62d6a468e2883421de654030c42c5af/src/ontology/mondo.Makefile#L641?
2. Deal with https://github.com/monarch-initiative/mondo/issues/4751? I still see sorting issues in your diff, see for example `src/ontology/mappings/mondo_exactmatch_mesh.sssom.tsv`.

Remember this pipeline is updated with every release, so we need to make sure that when Sabrina runs the release, the files get updated in the correct way.

2023-04-14 06:33 UTC, matentzn approved these changes

2023-04-14 06:33 UTC, merged