revise text def for MONDO:0100516
monarch-initiative/mondo pull request #6588
Opened 2023-08-23 17:57 UTC by megankraus

Closes #6502-revise-txt-def

2023-08-24 22:46 UTC, nicolevasilevsky approved these changes

2023-08-24 22:49 UTC, nicolevasilevsky requested changes
@megankraus can you please link the ticket to this term as a term tracker item?
see:
https://mondo.readthedocs.io/en/latest/editors-guide/f-entities/#term-tracker-item

2023-08-24 22:50 UTC, nicolevasilevsky commented
also - this ticket revises the comment, not the text definition. Could you please adjust the description accordingly?
thanks!

2023-08-31 17:04 UTC, megankraus commented
term tracker item

xsd:https://github.com/monarch-initiative/mondo/issues/6502

2023-09-01 22:49 UTC, sabrinatoro approved these changes

2023-09-01 23:35 UTC, merged