expert review: disorder of visual system
monarch-initiative/mondo pull request #6947
Opened 2023-12-04 19:51 UTC by nicolevasilevsky

[spreadsheet](https://docs.google.com/spreadsheets/d/1kFEDKYSbYq_SoO0BZp5u6VAlQzfaTaR-/edit#gid=610877821).

ROBOT Reviewer-Curator Agree - Stay
`sh run.sh make TEMPLATE_URL="https://docs.google.com/spreadsheets/d/e/2PACX-1vTo63mkIQGjS4wu1_ute8QwQCCTiTJuqDlzwJeiTqAdaMVSg7r-CqZkwYpoTLMiRA/pub?gid=610877821&single=true&output=tsv" merge_template -B`

ROBOT Reviewer-Curator Agree - Leave
`https://docs.google.com/spreadsheets/d/e/2PACX-1vTo63mkIQGjS4wu1_ute8QwQCCTiTJuqDlzwJeiTqAdaMVSg7r-CqZkwYpoTLMiRA/pub?gid=1411222162&single=true&output=tsv`

ROBOT Reviewer-Stay Curator-Leave
`sh run.sh make TEMPLATE_URL="https://docs.google.com/spreadsheets/d/e/2PACX-1vTo63mkIQGjS4wu1_ute8QwQCCTiTJuqDlzwJeiTqAdaMVSg7r-CqZkwYpoTLMiRA/pub?gid=804338695&single=true&output=tsv" merge_template -B`

2023-12-04 20:52 UTC, sabrinatoro requested changes
@nicolevasilevsky 
I see that all the new parents have been added, but I don't see any comments added, that is:
"ROBOT Reviewer-Curator Agree - Leave" Tab
!!!!!2 comments should be added manually

2023-12-04 21:27 UTC, nicolevasilevsky commented
> @nicolevasilevsky I see that all the new parents have been added, but I don't see any comments added, that is: "ROBOT Reviewer-Curator Agree - Leave" Tab !!!!!2 comments should be added manually

I'll take care of this

2023-12-04 21:35 UTC, nicolevasilevsky commented
done, ready for review.

Note, I deleted the existing comment on MONDO:0007334 autosomal dominant popliteal pterygium syndrome, it said to check the logical definition and the logical definition looks fine to me.

2023-12-05 00:15 UTC, sabrinatoro approved these changes

2023-12-05 00:24 UTC, merged