merge parkinsonism-dystonia, infantile, 2
monarch-initiative/mondo pull request #7090
Opened 2024-01-02 20:39 UTC by nicolevasilevsky

close #6933

2024-01-17 01:44 UTC, sabrinatoro requested changes
@nicolevasilevsky I have some questions about exact vs related synonyms.

2024-01-17 01:44 UTC, sabrinatoro commented on src/ontology/mondo-edit.obo
> +synonym: "Parkinsonism-dystonia, infantile, 2" RELATED [OMIM:618049]
should this be "exact" synonym?

2024-01-17 01:44 UTC, sabrinatoro commented on src/ontology/mondo-edit.obo
> +synonym: "PKDYS2" RELATED ABBREVIATION [OMIM:618049]
should this be "exact" synonym?

2024-01-19 02:02 UTC, nicolevasilevsky reviewed
updated per your comments, thanks!

2024-01-19 02:02 UTC, nicolevasilevsky commented on src/ontology/mondo-edit.obo
> +synonym: "Parkinsonism-dystonia, infantile, 2" RELATED [OMIM:618049]
yes, fixed

2024-01-19 02:02 UTC, nicolevasilevsky commented on src/ontology/mondo-edit.obo
> +synonym: "PKDYS2" RELATED ABBREVIATION [OMIM:618049]
yes, fixed

2024-01-20 01:42 UTC, sabrinatoro approved these changes
Thank you for updating. It looks good.

2024-01-20 01:42 UTC, merged