add new term ocular dysgenesis caused by defects in PAX6 regulation
monarch-initiative/mondo pull request #7151
Opened 2024-01-19 19:16 UTC by nicolevasilevsky

close #7066

2024-01-20 02:04 UTC, sabrinatoro requested changes
@nicolevasilevsky, I have a few comments.

2024-01-20 02:04 UTC, sabrinatoro commented on src/ontology/mondo-edit.obo
> -relationship: has_material_basis_in_germline_mutation_in http://identifiers.org/hgnc/1171 {source="MONDO:mim2gene_medgen"} ! ELP4
I don't think it is correct to remove this axiom. ELP4 is reported in OMIM:617141 to be associated with this disease.

2024-01-20 02:04 UTC, sabrinatoro commented on src/ontology/mondo-edit.obo
> -relationship: has_material_basis_in_germline_mutation_in http://identifiers.org/hgnc/19016 {source="MONDO:mim2gene_medgen"} ! TRIM44
It isn't correct to remove this axiom. TRIM44 is reported in OMIM:617142 to be associated with this disease.

2024-01-20 02:04 UTC, sabrinatoro commented on src/ontology/mondo-edit.obo
> -intersection_of: has_material_basis_in_germline_mutation_in http://identifiers.org/hgnc/19016 ! TRIM44
It isn't correct to remove this axiom. TRIM44 is reported in OMIM:617142 to be associated with this disease.

2024-01-22 01:21 UTC, nicolevasilevsky commented on src/ontology/mondo-edit.obo
> +relationship: has_material_basis_in_germline_mutation_in http://identifiers.org/hgnc/8620 {source="https://clinicalgenome.org/affiliation/40077/", source="https://orcid.org/0000-0001-5935-2391"} ! PA
I removed this

2024-01-22 01:23 UTC, nicolevasilevsky commented on src/ontology/mondo-edit.obo
> +is_a: MONDO:0100534 {source="https://clinicalgenome.org/affiliation/40077/", source="https://orcid.org/0000-0001-5935-2391"} ! ocular dysgenesis caused by defects in PAX6 regulation
I revised the logical axiom

2024-01-22 01:24 UTC, nicolevasilevsky commented
ready for re-review

2024-01-23 00:03 UTC, sabrinatoro approved these changes
all my requests have been addressed. Approving and merging

2024-01-23 00:03 UTC, merged