Updated MedGen ROBOT template
monarch-initiative/mondo pull request #7467
Opened 2024-03-24 23:37 UTC by joeflack4

- Update: MedGen ROBOT template - with some fixes, updates, and now also includes MeSH mappings

2024-03-24 23:43 UTC, joeflack4 reviewed
@matentzn Just double checking, we don't need to worry about "conflicts" anymore, right? At this point, we're trusting MedGen as the source for these mappings, yes?

<details><summary>Context: Previous ad-hoc MedGen conflicts goals</summary>
<p>

```make
# MedGen conflicts (Aug 2023) pipeline
# - https://github.com/monarch-initiative/mondo-ingest/issues/273
.PHONY: address-medgen-conflicts-aug2023
address-medgen-conflicts-aug202x3: address-medgen-conflicts-aug2023-deletes address-medgen-conflicts-aug2023-adds

# - MedGen conflicts: dependencies
tmp/July2023_CUIReports_FromMedGentoMondo.xlsx:
    mkdir -p tmp && wget "https://github.com/monarch-initiative/mondo-ingest/files/12029712/July2023_CUIReports_FromMedGentoMondo.xlsx" -O $@

# - MedGen conflicts: analysis
tmp/mondo-edit.obo.tmp.diff: mondo-edit.obo.tmp
    -diff mondo-edit.obo mondo-edit.obo.tmp > $@

tmp/report-qc-medgen-conflicts-update-diff.tsv: tmp/mondo-edit.obo.tmp.diff
    python ../scripts/medgen_conflicts_removals_diff_analysis.py -i tmp/mondo-edit.obo.tmp.diff -o $@

tmp/report-qc-medgen-conflicts-adds-diff.tsv: $(TEMPLATES_DIR)/ROBOT_addMedGen_fromConflictResolution.tsv $(TEMPLATES_DIR)/ROBOT_addMedGen_fromIngest.tsv
    python ../scripts/medgen_conflicts_add_xrefs_diff_analysis.py -c $(TEMPLATES_DIR)/ROBOT_addMedGen_fromConflictResolution.tsv -i $(TEMPLATES_DIR)/ROBOT_addMedGen_fromIngest.tsv -o $@

# - MedGen conflicts: deletes
.PHONY: address-medgen-conflicts-aug2023-deletes
address-medgen-conflicts-aug2023-deletes: mondo-edit.obo.tmp
    mv mondo-edit.obo.tmp mondo-edit.obo

mondo-edit.obo.tmp: tmp/July2023_CUIReports_FromMedGentoMondo.xlsx mondo-edit.obo
    python ../scripts/medgen_conflicts_removals.py -i tmp/July2023_CUIReports_FromMedGentoMondo.xlsx -I mondo-edit.obo -o $@

# - MedGen conflicts: adds
.PHONY: address-medgen-conflicts-aug2023-adds
address-medgen-conflicts-aug2023-adds: tmp/report-qc-medgen-conflicts-adds-diff.tsv

$(TEMPLATES_DIR)/ROBOT_addMedGen_fromConflictResolution.tsv: tmp/July2023_CUIReports_FromMedGentoMondo.xlsx
    python ../scripts/medgen_conflicts_add_xrefs.py -i tmp/July2023_CUIReports_FromMedGentoMondo.xlsx -o $@

$(TEMPLATES_DIR)/ROBOT_addMedGen_fromIngest.tsv:
    wget "https://github.com/monarch-initiative/medgen/releases/latest/download/medgen-xrefs.robot.template.tsv" -O $@

```

</p>
</details>

2024-03-25 08:40 UTC, matentzn commented
> @matentzn Just double checking, we don't need to worry about "conflicts" anymore, right? At this point, we're trusting MedGen as the source for these mappings, so I don't need to run any such analysis, yes?

Thats right, thanks for checking! We are just trusting for now!

2024-03-25 08:43 UTC, matentzn requested changes
-  Remove all rows with MEDGENCUI in it (we only need xrefs to MEDGEN:123 and UMLS:123)

(you checked the box in the ticket, but rows are still in there)

2024-03-26 20:50 UTC, joeflack4 commented
> (you checked the box in the ticket, but rows are still in there)
@matentzn Glad to have your eyes on these, sorry about my error rate!

What happened here is that I did check multiple times on the MedGen side of things, but I marked the release as a "pre release". I thought it still carried the "latest" tag after that, but it removed it. So when I ran the goal here, it did not select the correct release, and I didn't check the results.

I fixed that issue, re-ran it, and confirmed there is no more MEDGENCUI.

2024-04-11 21:46 UTC, joeflack4 commented
@matentzn I made the appropriate changes in https://github.com/monarch-initiative/medgen/pull/19 and updated the file here. I think this should be good now; maybe take a look. You can also examine as a google sheet: https://docs.google.com/spreadsheets/d/1OD7WUR-nJ9lUqRv01TTghmf3aGvQRbWV5ZhVhthzB6U/edit#gid=1627855620

2024-04-12 08:22 UTC, twhetzel reviewed
I reviewed the content in the gSheet linked in [PR](https://docs.google.com/spreadsheets/d/1OD7WUR-nJ9lUqRv01TTghmf3aGvQRbWV5ZhVhthzB6U/edit#gid=1627855620). 

When the `xref_id` value is from MESH, there are many cases where the same MESH identifier, e.g. `MESH:C000719212` exists more than once in the ROBOT file for different Mondo IDs, e.g. `MONDO:0000600` and `MONDO:0003736` which I thought caused a proxy merge and was not allowed.

2024-04-12 08:38 UTC, twhetzel commented
I chatted with @matentzn and the current thought is that the medgen xrefs can be added now, but not the mesh ones.

2024-04-13 21:03 UTC, twhetzel commented
NOTE: The issue of proxy merges is being discussed with MedGen is this issue https://github.com/monarch-initiative/mondo-ingest/issues/491

2024-05-03 11:19 UTC, matentzn requested changes
Please split the table into MEDGEN and MESH as per https://github.com/monarch-initiative/mondo/pull/7467#issuecomment-2051296965 by @twhetzel, then this is ready.

2024-05-04 04:44 UTC, joeflack4 commented
- [ ] @joeflack4 `medgen` repo: Move MeSH xrefs into a secondary robot template which will not currently be used.
- [ ] @joeflack4 `mondo` repo: Pull down into this PR the new, updated original robot template, which will no longer have MeSH xrefs

@matentzn @twhetzel I misunderstood what Trish wrote. I thought this meant that whoever was running the robot template to operate on `mondo-edit.obo` would do something to avoid merging in the MeSH terms, and that this was an FYI. I understand the task now. Easy fix; will get to this next week!

2024-05-08 22:49 UTC, joeflack4 commented
I've completed [the tasks](https://github.com/monarch-initiative/mondo/pull/7467#issuecomment-2094008926) for splitting out MeSH xrefs as requested. Now ready for re-review / merge.

Completed by:
- https://github.com/monarch-initiative/medgen/pull/26

2024-05-09 08:55 UTC, matentzn commented
Looks awesome! But where is the code to support this change? It does not seem to be in this PR?

2024-05-15 12:13 UTC, joeflack4 commented
@matentzn This is [ready to be merged](https://github.com/monarch-initiative/mondo/pull/7467#issuecomment-2102243758), but I think you still need to mark resolved your [requested changes](https://github.com/monarch-initiative/mondo/pull/7467#pullrequestreview-2037933418).

The requested change (split MeSH out) has been completed:
1. here in this PR
2. In the related [MedGen PR](https://github.com/monarch-initiative/medgen/pull/26) (merged already)

2024-05-15 12:34 UTC, matentzn commented
This PR has a single file in the diff with MESH and Medgen xrefs together - this does not seem to confirm changes are adressed?

2024-05-16 00:20 UTC, joeflack4 commented on src/templates/ROBOT_addMedGen_fromIngest.tsv
## Review update as of 2024/05/15
Thanks @matentzn for teaching me how to comment on a file rather than a line. Let's use this thread to avoid clutter.

[Nico wrote](https://github.com/monarch-initiative/mondo/pull/7467#issuecomment-2112405833):
> This PR has a single file in the diff with MESH and Medgen xrefs together - this does not seem to confirm changes are addressed?

I was really surprised to see you say that! And you're right. I did the old mistake of trusting normal things to not work and, seeing my [MedGen repo release](https://github.com/monarch-initiative/medgen/releases/tag/v2024-05-08) coming out OK, I ran the command to do the `wget` over here, and updated this PR, thinking the output worked without checking it.

But that didn't work. Two weird things appear to have happened, and I'm not sure why. I think (1) was sufficient to cause the issue of this file no getting updated, but (2) is also strange.

You probably don't have time to read the below, but I really wanted to know why this didn't update correctly. So feel free to skip if you don't have time.

### 1. Release not marked `latest`
<details><summary>Details</summary>
<p>

The [release](https://github.com/monarch-initiative/medgen/releases/tag/v2024-05-08) I pushed out somehow didn't get activated as `latest`. So when I ran the goal to update in `mondo`, it used the wrong release.
  - Another curious thing is that, even though this release happened on 5/08, it was still showing at the very top of [releases](https://github.com/monarch-initiative/medgen/releases), even though (i) it was not the release labeled with `latest`, and (ii) it was showing up above the newer release on 5/12. I've since ran a new release today 5/15, and that one is correctly showing as `latest` and also shows at the top of the page.
  - As an aside, you may notice that the release that was _supposed_ to have been `latest` when I did `wget` had the date format `vYYYY-MM-DD`, while most of the other releases had `YYYY-MM-DD`. I just fixed this inconsistency with [this commit](https://github.com/monarch-initiative/medgen/commit/995968c6548821a92f173762d245acdf12acfe80). Basically the one with the `v` was the result of running `deploy-release` locally, and the other ones are from the GitHub action. Perhaps the fact that it was `deploy-release` was why it didn't tag it as `latest`, but I don't see why.

</p>
</details> 

### 2. Git commit of release wrong?
<details><summary>git log</summary>
<p>

The git commit of some recent releases is not what I would expect.

```git-log
commit 989160fcb1b2c0ce7ebace1fe791d47d10d6cea2 (tag: 2024-05-15)
Date:   Wed May 15 19:42:46 2024 -0400
    - Add: MeSH robot template to release

commit 23c78aeadc409fa8faa9f439c76e5caa0eb66012
Date:   Sun May 12 21:45:54 2024 -0400
    Merge pull request #26 from monarch-initiative/split-mesh

commit 11f03ffbf6cc073b8789d9117088481d9a0676a9 (origin/split-mesh)
Date:   Wed May 8 18:17:20 2024 -0400
    Split MeSH outputs

commit c0bb5f43391051e0deca596c6287b7cb3a5aac99 (tag: v2024-05-08, tag: 2024-05-12, tag: 2024-05-05)
Date:   Sun Apr 28 17:07:31 2024 -0400
    Merge pull request #25 from monarch-initiative/fix-odk-version
```

I merged my PR after these releases ran `(tag: v2024-05-08, tag: 2024-05-12, tag: 2024-05-05)`. So I'm not surprised by 5/05 and 5/12 using my unmerged code. but `v2024-05-08`, I would think I ran it from the correct commit... I must have run it accidentally from `main`. However, if I download the `medgen-xrefs.robot.template.tsv` from that release, it shows no MeSH mappings! So either the commit it's showing is wrong, or I ran it on `main` and then I edited the release with the correct outputs from my PR that hadn't been merged yet, which I don't remember doing. Really strange. And since `medgen-xrefs.robot.template.tsv` was correct here, than I would have expected the `wget` to have gotten the correct file. So the cause of the issue msut be (1). 

</p>
</details>

2024-05-23 12:06 UTC, matentzn approved these changes
Looks good to me!

2024-05-23 23:41 UTC, merged