Add information about the identifiers used by Mondo to the README
monarch-initiative/mondo pull request #7478
Opened 2024-03-25 22:13 UTC by gaurav

I noticed that the information on constructing a Mondo identifier is currently located in two places:
1. http://obofoundry.org/id-policy says that the URI `"http://purl.obolibrary.org/obo/" IDSPACE "_" LOCALID` should be used.
2. https://mondo.readthedocs.io/en/latest/editors-guide/f-entities/ says that "All classes are in MONDO ID space"

I really like how the [LOINC User Guide (in section 12.7.2)](https://loinc.org/kb/users-guide/recommendations-for-best-practices-in-using-and-mapping-to-loinc/#using-a-uri-to-identify-loinc-concepts-as-resources-in-rdf) clearly describes how to construct an RDF URI for a LOINC concept, and I think it would be great to include this information in Mondo's documentation somewhere.

In this PR I propose a short paragraph on the main README page in a new section entitled "Identifiers" that would contain this information. If there is a better place to place this document (e.g. the editor's guide linked to above), let me know and I'll make a PR to target that file itself. Feel free to change my proposed wording or move it another file if that would be better.

2024-03-29 13:12 UTC, matentzn requested changes
This content is correct and very much appreciated, but it needs to go into the "Mondo user guide". I can only find an editors guide and a developer guide.

@nicolevasilevsky What would be the best place to put such content? Should we start building a "user guide"?

2024-03-29 21:36 UTC, nicolevasilevsky commented
on our readthedocs documentation, we actually have a "user's corner" on the left hand nav, but I have my doubts if many users know that is there.

<img width="252" alt="image" src="https://github.com/monarch-initiative/mondo/assets/6722114/a670e111-4f60-4973-909e-7c46c5b59693">

I've always thought the [website](https://mondo.monarchinitiative.org/) was meant to be more of the user documentation. But then there was talk at some point about merging the website and the readthedocs site, which I am in favor of.

I think a more prominent users guide is a great idea. 

At C-Path, we are going to have a week-long hackathon in a few weeks where we are going to focus on documentation. Maybe Mondo should consider a 1 or 2 day hackathon to focus on revising + updating documentation and aggregating and reorganizing all of the docs?

2024-03-29 22:17 UTC, twhetzel requested changes
small change requested

2024-04-04 15:08 UTC, gaurav commented
My FHIR RDF colleagues pointed out one other thing I missed in addition to Trish's feedback:
- [ ] Add a note either here or on the [MONDO codesystem page on terminology.hl7.org](https://terminology.hl7.org/CodeSystem-MONDO.html) asking users to use MONDO identifiers instead of CURIEs, i.e. when representing MONDO:0005015 "diabetes mellitus" in FHIR, they should use `system=http://purl.obolibrary.org/obo/mondo.owl` and `code=0005015` rather than `code=MONDO:0005015` (see discussion at https://github.com/w3c/hcls-fhir-rdf/issues/127).

2024-05-02 06:13 UTC, gaurav commented on README.md
> +compact URIs with the prefix `MONDO:`, such as `MONDO:0005015`, as required by the
How about `... compact URIs ([CURIEs](https://en.wikipedia.org/wiki/CURIE)) with ...`? I like the idea of readers being able to learn more about CURIEs if they're not familiar with the term.

2024-05-02 06:23 UTC, gaurav commented
@nicolevasilevsky:
> on our readthedocs documentation, we actually have a "user's corner" on the left hand nav, but I have my doubts if many users know that is there. Screenshot pasted below

I've updated this PR [add an 'Identifiers' page](https://github.com/monarch-initiative/mondo/blob/3a05a22c2daca4f43372030089178a4719f2de6c/docs/editors-guide/identifiers.md) to the Mondo User Guide -- I'm not sure what other content would make sense on that page, but if this approach makes more sense than adding this paragraph to the README, then that would be fine by me too!

2024-05-02 10:48 UTC, matentzn approved these changes
Lets merge this and reconsider it during our Mondo documentation hackathon in June!

2024-05-03 16:36 UTC, nicolevasilevsky commented
> Lets merge this and reconsider it during our Mondo documentation hackathon in June!

when is the hackathon in June?

2024-05-03 16:51 UTC, matentzn commented
> when is the hackathon in June?

No date yet.

2024-05-16 23:11 UTC, gaurav commented on README.md
> +compact URIs with the prefix `MONDO:`, such as `MONDO:0005015`, as required by the
@twhetzel Just wanted to check if this change (from 407924f) addressed your concern here, Trish! If not, I'm happy to go with your formulation.

2024-05-16 23:12 UTC, gaurav commented
> Lets merge this and reconsider it during our Mondo documentation hackathon in June!

That sounds good to me, but of course I don't get a vote :)

2024-05-17 00:46 UTC, twhetzel commented on README.md
> +compact URIs with the prefix `MONDO:`, such as `MONDO:0005015`, as required by the
yes, that looks great!

2024-05-19 08:42 UTC, merged

2024-05-19 08:43 UTC, matentzn commented
@gaurav thank you for your patience and contribution here! Really sorry it took so long! We highly appreciate any further suggestions as well :)