excluded superclasses that have MONDO-XXXXXXX-obsoleted source
monarch-initiative/mondo pull request #7523
Opened 2024-04-02 23:08 UTC by nicolevasilevsky

address #6004

@sabrinatoro

- I will slowly work on cleaning up these superclasses that were rewired
- If I disagree with the subclass, I made it an excluded subclass with my ORCID
- if I agree with the superclass assertion, I added my ORCID
- I cleaned up a few definitions too

2024-04-03 17:51 UTC, sabrinatoro requested changes
@nicolevasilevsky 
There are a few examples where I think "exclude_subclassOf" is incorrect because it would be excluding a grandparent term. 

In other cases, I "think" it is ok, but I am not an expert. Therefore I am wondering whether it wouldn't be better to remove these subClassOf (instead of excluding them), so we don't restrict future potential parentage. I will add this specific point to be discussed on a curation call.

2024-04-03 17:51 UTC, sabrinatoro commented on src/ontology/mondo-edit.obo
> +relationship: excluded_subClassOf MONDO:0005093 {source="MONDO:0018798-obsoleted", source="https://orcid.org/0000-0001-5208-3432"} ! skin disorder
another parent is "dermis disorder", which is a "skin disorder". So excluded this SC does not make sense. 

Also this term is a "anhidrosis" (= sweat gland disorder) "with normal sweat gland". 

This term requires more review, but at minimum, we should either not exclude SC "skin disorder", or also exclude SC "dermis disorder"

2024-04-03 17:51 UTC, sabrinatoro commented on src/ontology/mondo-edit.obo
> +relationship: excluded_subClassOf MONDO:0005267 {source="MONDO:0015506-obsoleted", source="https://orcid.org/0000-0001-5208-3432"} ! heart disorder
'heart disorder' is a great-grandparent. We can remove this parent, but we should not add as an "ecluded_SC"

2024-04-03 17:51 UTC, sabrinatoro commented on src/ontology/mondo-edit.obo
> +relationship: excluded_subClassOf MONDO:0018230 {source="MONDO:0019709-obsoleted", source="https://orcid.org/0000-0001-5208-3432"} ! skeletal dysplasia
I would remove but not "exclude_SC"
The parent "osteochondrodysplasia" seems that is should be "skeletal dysplasia" (though it currently is not).

2024-04-16 15:35 UTC, nicolevasilevsky commented
We can close this, we'll address this with the action items in the ticket (https://github.com/monarch-initiative/mondo/issues/6004#issuecomment-2038336961).

2024-04-16 15:35 UTC, closed without merging