Modify hereditary hemophagocytic lymphohistiocytosis
monarch-initiative/mondo pull request #7662
Opened 2024-05-02 03:42 UTC by twhetzel

closes #7437

@sabrinatoro can you check if I've made the correct changes based on the [last comment ](https://github.com/monarch-initiative/mondo/issues/7437#issuecomment-2025921543)in the ticket?

2024-05-03 01:36 UTC, twhetzel commented
@sabrinatoro I don't see your comments. Did you finish the review?

2024-05-03 15:35 UTC, sabrinatoro commented
@twhetzel I didn't comment about the synonyms. But for the synonyms with the orphanet to be exclude, please keep them (because we might have reviewed them previously and OKed them and we didn't keep track of it).

2024-05-03 16:50 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +relationship: excluded_subClassOf MONDO:0015541 {source="Orpha:158038"} ! hereditary hemophagocytic lymphohistiocytosis
done

2024-05-03 17:00 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +subset: orphanet_rare {source="Orphanet:540"}
done

2024-05-03 17:10 UTC, twhetzel commented on src/ontology/mondo-edit.obo
>  is_a: MONDO:0003778 {source="https://orcid.org/0000-0001-5208-3432"} ! inborn error of immunity
@sabrinatoro to add back `xref: Orphanet:158038 `, what should the source be?

2024-05-03 17:11 UTC, sabrinatoro commented on src/ontology/mondo-edit.obo
>  is_a: MONDO:0003778 {source="https://orcid.org/0000-0001-5208-3432"} ! inborn error of immunity
no source

2024-05-03 17:14 UTC, twhetzel commented on src/ontology/mondo-edit.obo
>  is_a: MONDO:0003778 {source="https://orcid.org/0000-0001-5208-3432"} ! inborn error of immunity
the others are updated, but have not had confirmation of these steps from @nicolevasilevsky yet

2024-05-03 18:39 UTC, nicolevasilevsky commented on src/ontology/mondo-edit.obo
>  is_a: MONDO:0003778 {source="https://orcid.org/0000-0001-5208-3432"} ! inborn error of immunity
sounds good! Thanks to you both!

2024-05-03 18:40 UTC, nicolevasilevsky approved these changes

2024-05-03 19:07 UTC, sabrinatoro requested changes
@twhetzel 
The following should be kept (they still look as removed), because we might have reviewed and agreed to these synonyms, but we did not indicate it. In addition, we should keep that GARD, even if the orphanet is excluded.
![Screenshot 2024-05-03 at 12 04 06 PM](https://github.com/monarch-initiative/mondo/assets/12737987/962cde61-8ee5-46e9-b01f-e7eae8983d60)

Also, please make sure to resolve the QC fail. 
Thanks

2024-05-03 20:48 UTC, twhetzel commented
Addressed CR (change request)

2024-05-10 14:05 UTC, sabrinatoro requested changes
just a few things to change

2024-05-11 23:35 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +relationship: excluded_subClassOf MONDO:0015541 {source="Orphanet:158038", source="https://orcid.org/0000-0001-9310-0163"} ! hereditary hemophagocytic lymphohistiocytosis
done

2024-05-11 23:40 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +xref: GARD:20025
done

2024-05-11 23:41 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +relationship: excluded_subClassOf MONDO:0015541 {source="Orphanet:158038", source="https://orcid.org/0000-0001-9310-0163"} ! hereditary hemophagocytic lymphohistiocytosis
How is `Orpha:158038` excluded in Mondo as a grouping term that is not in scope in Mondo from [this comment](https://github.com/monarch-initiative/mondo/issues/7437#issuecomment-2025921543)?

2024-05-14 14:11 UTC, sabrinatoro commented on src/ontology/mondo-edit.obo
> +relationship: excluded_subClassOf MONDO:0015541 {source="Orphanet:158038", source="https://orcid.org/0000-0001-9310-0163"} ! hereditary hemophagocytic lymphohistiocytosis
You need to add this x-ref in the "excluded" file for Orphanet. I will add a note in the issue.

2024-05-14 14:12 UTC, sabrinatoro approved these changes
Everything looks good. Approving and merging.

2024-05-14 14:12 UTC, merged