add term hyperinsulinemic hypoglycemia with polycystic kidney disease
monarch-initiative/mondo pull request #7688
Opened 2024-05-07 05:25 UTC by twhetzel

closes #7457

2024-05-08 21:05 UTC, sabrinatoro requested changes
Please see comments for the requested changes.
The main requested change is the definition which would be re-written as it is currently confusing and misleading. I suggest that you share the definition with the person who requested the term to make sure that they agree with it.

2024-05-08 21:05 UTC, sabrinatoro commented on src/ontology/mondo-edit.obo
> +def: "Rare, heterogeneous disorders that co-occur do to a mutation in the phosphomannomutase 2 gene (PMM2)." [PMID:28373276, PMID:36412659]
the ClinGen Working Group should be added to the dbxref for the definition.

2024-05-09 04:56 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +def: "Rare, heterogeneous disorders that co-occur do to a mutation in the phosphomannomutase 2 gene (PMM2)." [PMID:28373276, PMID:36412659]
I updated the definition and added the source.

2024-05-09 04:57 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +is_a: MONDO:0005803 ! hyperinsulinemic hypoglycemia
done

2024-05-09 14:41 UTC, sabrinatoro commented
@twhetzel I am still suspicious about the definition and about any "autosomal recessive disorder by this specific variant" to be "hyperinsulinemic hypoglycemia with polycystic kidney disease". On the other hand, does it mean that there is absolutely no other cause for this disease? Shouldn't the definition mention the fact that it is a hyperinsulinemic hypoglycemia for example.

Definitions should be discussed and approved by the requestor before we can approve/add a new term to master (once it is in the ontology, it is official). So please get the approval by the requestor first.

2024-05-09 16:16 UTC, twhetzel commented
@sabrinatoro I asked in the review comment that you review the updated definition before I post in the issue ticket. I gather you have done this so I've now asked the requestor for feedback. Based on the limited information I can find about this disease, this is the best I can suggest.

2024-05-11 22:47 UTC, twhetzel commented
This PR is on hold until the definition is [verified](https://github.com/monarch-initiative/mondo/issues/7457#issuecomment-2102970216) by the user who submitted the term.

2024-05-17 00:53 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +def: "Rare, heterogeneous disorders that co-occur do to a mutation in the phosphomannomutase 2 gene (PMM2)." [PMID:28373276, PMID:36412659]
The user [agreed](https://github.com/monarch-initiative/mondo/issues/7457#issuecomment-2116152998) to the definition.

2024-05-17 02:30 UTC, twhetzel commented
This is ready for review.

2024-05-17 22:54 UTC, sabrinatoro approved these changes
looks good. Approving and merging.

2024-05-17 22:54 UTC, merged