Revise/correct a few non-human animal infectious disease labels
monarch-initiative/mondo pull request #7710
Opened 2024-05-13 18:03 UTC by katiermullen

Closes #7709

2024-05-13 22:02 UTC, sabrinatoro requested changes
@katiermullen 
A few comments about adding the animal affected taxon in the Logical definition. 
Remember that if you add only "infectious diseases, non human animals' and some infectious agent NCBITaxon###", then you mean that it is for any non-human.

I don't understand why you had to add the "viral non-human disease" as an asserted parent. It is not incorrect to add it, but you should "get it for free". Maybe we need to update the import for this infectious agent.

2024-05-14 02:45 UTC, katiermullen commented on src/ontology/mondo-edit.obo
>  relationship: in_taxon NCBITaxon:9681 {source="PMID:9364228", source="https://orcid.org/0000-0002-4142-7153", source="https://orcid.org/0000-0002-5002-8648", source="https://www.merckvetmanual.com/"}
done

2024-05-14 02:51 UTC, katiermullen commented on src/ontology/mondo-edit.obo
>  relationship: in_taxon NCBITaxon:9681 {source="PMID:1382145", source="PMID:9364228", source="https://orcid.org/0000-0002-4142-7153", source="https://orcid.org/0000-0002-5002-8648"} ! Felidae
done

2024-05-14 02:56 UTC, katiermullen commented on src/ontology/mondo-edit.obo
>  relationship: in_taxon NCBITaxon:9940 {source="https://orcid.org/0000-0002-4142-7153", source="https://orcid.org/0000-0002-5002-8648", source="https://www.merckvetmanual.com/"} ! Ovis aries
done

2024-05-14 03:00 UTC, katiermullen commented on src/ontology/mondo-edit.obo
>  intersection_of: MONDO:0100332 NCBITaxon:28344 ! disease has primary infectious agent Porcine reproductive and respiratory syndrome virus
done

2024-05-14 03:04 UTC, katiermullen commented on src/ontology/mondo-edit.obo
>  relationship: in_taxon NCBITaxon:9823 {source="https://orcid.org/0000-0002-4142-7153", source="https://orcid.org/0000-0002-5002-8648"} ! Sus scrofa
done

2024-05-14 03:12 UTC, katiermullen commented on src/ontology/mondo-edit.obo
>  intersection_of: MONDO:0100332 NCBITaxon:11232 ! disease has primary infectious agent
I think this is an error. The EC should be 'infectious disease, non-human animal'
 and ('disease has primary infectious agent' some 'canine distemper virus'). Do I need to update the import to include 'canine distemper virus'? If so, can you please tell me how :) Thank you!

2024-05-14 23:10 UTC, sabrinatoro approved these changes
looks good to me. Good job, @katiermullen

2024-05-14 23:10 UTC, merged