Remove subclassof terms
monarch-initiative/mondo pull request #7876
Opened 2024-06-27 21:43 UTC by yshwetar

closes #7639

Removed subclass of terms 'telomere syndrome' and 'dysotosis' for fanconi anemia

2024-06-28 18:13 UTC, sabrinatoro requested changes
@yshwetar some changes are required. Please see the comment for more explanation.

2024-06-28 18:13 UTC, sabrinatoro commented on src/ontology/mondo-edit.obo
> -is_a: MONDO:0100137 {source="PMID:29804726"} ! telomere syndrome
@yshwetar we do not only remove the SubClassOf, we need to keep track of what SubClassOf we remove, including the original source and your orcid (to indicate you reviewed it)
Please see instructions here: https://mondo.readthedocs.io/en/latest/editors-guide/g-logical-axioms/#excluded-subclassof:~:text=non%2Dlogical)%20axiom.-,Excluded%20subclassOf,%C2%B6,-Rather%20than%20removing

2024-06-28 18:13 UTC, sabrinatoro commented on src/ontology/mondo-edit.obo
> -is_a: MONDO:0100137 {source="PMID:29804726"} ! telomere syndrome
note the addition of your orcid as a source for the "excluded subclass of" is not in the documentation yet (it is a relatively new sop)

2024-07-09 18:56 UTC, yshwetar commented
Closing as this issue #7639 was addressed by the PR #7892

2024-07-09 18:56 UTC, closed without merging