New term Vertebral Artery Dissection
monarch-initiative/mondo pull request #7895
Opened 2024-07-01 21:39 UTC by yshwetar

Closes #7593

Following in new term

- Definition with 1 PMID
- 2 PMID dbxref
- Child term of cervical artery dissection

2024-07-04 00:22 UTC, sabrinatoro requested changes
@yshwetar I added some comments to bring your attention to some things to keep in mind. Mostly related to x-refs and source missing for the SubclassOf.

That being said, I don't think this term being requested should be added into Mondo because it is not a disease. As the definition states, it is a "rare cause of stroke", and is probably more of a condition or an event. See more information about exclusion reasons [here](https://mondo.readthedocs.io/en/latest/editors-guide/exclusion-reasons/)
What do you think?

2024-07-04 00:22 UTC, sabrinatoro commented on src/ontology/mondo-edit.obo
> +xref: PMID:19096659
xref should refer to an ID in another terminology (e.g. OMIM:##, Orphanet:###). Not PMID. 
PMID can be used as an annotation to a definition or synonym

2024-07-04 00:22 UTC, sabrinatoro commented on src/ontology/mondo-edit.obo
> +xref: PMID:33659122
xref should refer to an ID in another terminology (e.g. OMIM:##, Orphanet:###). Not PMID. 
PMID can be used as an annotation to a definition or synonym

2024-07-04 00:22 UTC, sabrinatoro commented on src/ontology/mondo-edit.obo
> +is_a: MONDO:0006061 ! cervical artery dissection
source annotation is missing

2024-07-09 18:52 UTC, yshwetar commented
Closing this branch as we concluded VAD is not a disease, and an external factor, #7593

2024-07-09 18:52 UTC, closed without merging