Add synonyms
monarch-initiative/mondo pull request #7915
Opened 2024-07-03 15:37 UTC by matentzn

close #7834

2024-07-03 17:53 UTC, nicolevasilevsky commented on src/ontology/mondo-edit.obo
> +synonym: "full neurofibromatosis type 2" EXACT [Orphanet:637]
Please add the dbxef that was requested on the ticket: https://www.ncbi.nlm.nih.gov/books/NBK1201/

2024-07-03 17:54 UTC, nicolevasilevsky commented on src/ontology/mondo-edit.obo
> +synonym: "neurofibromatosis 1" EXACT [NCIT:C3273, NORD:1502]
these changes were not requested on the ticket and are not mentioned in the commit message. Could you please explain these additional changes?
Thanks!

2024-07-03 17:54 UTC, nicolevasilevsky requested changes
See comment inline, minor changes needed. Thanks for adding these synonyms and addressing this ticket.

2024-07-11 23:18 UTC, nicolevasilevsky commented on src/ontology/mondo-edit.obo
> +synonym: "full neurofibromatosis type 2" EXACT [Orphanet:637]
done

2024-07-11 23:20 UTC, nicolevasilevsky commented
@twhetzel can you please review this PR?

Note, I also added some synonyms to type 1, for teaching purposes at the ICBO tutorial

2024-07-15 23:19 UTC, twhetzel approved these changes

2024-07-15 23:20 UTC, twhetzel commented
@nicolevasilevsky since you formally requested changes in this PR, you'll need to approve also.

2024-07-15 23:43 UTC, nicolevasilevsky approved these changes

2024-07-15 23:43 UTC, merged