WIP: Adding Japanese translation to Mondo
monarch-initiative/mondo pull request #7928
Opened 2024-07-06 10:07 UTC by matentzn

Some initial experiments adding an international version of Mondo with translations, but mostly for later this year, not now.

2025-03-25 16:58 UTC, matentzn commented
Yes correct, only you can review this (changes are all highly technical), but I am not sure if it's worth your time until we get a decision we want to go ahead with this..

2025-03-25 18:02 UTC, twhetzel commented
Ok, let me know when this should be reviewed.

2025-03-26 20:44 UTC, twhetzel commented
We decided in Slack this should be reviewed and added for the upcoming April release.

2025-03-26 21:09 UTC, twhetzel commented on src/ontology/mondo.Makefile
> +	$(MAKE) $(TRANSLATION_FILES)
@matentzn in Slack you mentioned this was folded into the release pipeline. Where is that done?

2025-03-26 21:11 UTC, twhetzel requested changes
I ran `sh run.sh make translations -B` to test this, but ran into this error:

```
make[1]: *** [Makefile:735: mirror-ncbigene] Error 1
rm imports/foodon_terms.txt imports/omo_terms.txt imports/ncbigene_terms.txt imports/envo_terms.txt imports/ncit_terms.txt
make[1]: Leaving directory '/work/src/ontology'
make: *** [mondo.Makefile:1322: translations] Error 2
```

2025-03-26 21:14 UTC, matentzn commented
This goal should be deleted, I only used it during testing. Make mondo-international.owl (with IMP=false etc)

2025-03-26 21:14 UTC, twhetzel commented on src/ontology/mondo.Makefile
> +	$(MAKE) $(TRANSLATION_FILES)
Answered [above](https://github.com/monarch-initiative/mondo/pull/7928/files#r2015006091) - it's part of `MAIN_PRODUCTS`

2025-03-26 21:17 UTC, twhetzel commented
Ok, I will delete the goal `translations` and test with `make mondo-international.owl`

2025-03-26 21:49 UTC, twhetzel requested changes
I re-ran as `sh run.sh make mondo-international.owl IMP=false MIR=false PAT=false -B`

Error:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
make: *** [mondo.Makefile:1334: ../translations/mondo-jp-preprocessed.babelon.tsv] Error 1
```

2025-03-27 16:24 UTC, twhetzel commented
@matentzn there is an error running the `make` goal.

2025-03-27 17:58 UTC, twhetzel commented
@matentzn following your email, I re-ran the goal as:  `sh run.sh make mondo-international.owl IMP=false MIR=false` and that did work.  

However, when I run the goal as: `sh run.sh make mondo-international.owl IMP=false MIR=false -B` that does not work with the same error I posted earlier.
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
make: *** [mondo.Makefile:1330: ../translations/mondo-jp-preprocessed.babelon.tsv] Error 1
```

The full logs are attached.

Are you able to get the goal to run when using `-B`?
[LOGS_japanese-translation.txt](https://github.com/user-attachments/files/19491688/LOGS_japanese-translation.txt)

2025-03-28 17:41 UTC, twhetzel approved these changes
With updates to the file from DBCLS (https://github.com/dbcls/mondo-japanese/issues/2) I was able to now run the goal successfully as:
`sh run.sh make mondo-international.owl IMP=false MIR=false -B`

2025-03-28 17:42 UTC, merged