Add 52 manually curated SNOMED mappings to Mondo - Take 2
monarch-initiative/mondo pull request #7950
Opened 2024-07-12 02:00 UTC by twhetzel

I talked with Blake to sort out the proxy merge issues, but the ORCIDs were also incorrect. These issues were all updated in the gSheet so I ran the ROBOT template against `mondo-edit.obo` in a new branch to fix all issues in bulk.

The original PR is at: https://github.com/monarch-initiative/mondo/pull/7817

2024-07-13 00:11 UTC, twhetzel commented
To fix the proxy merges, I discussed with Nicole and she suggested to remove the `MONDO:equivalentTo` on the xrefs that were no longer the preferred xref values based on the data used to create these new xrefs.

2024-07-23 03:34 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +xref: SCTID:44359008 {source="https://orcid.org/0009-0002-1597-2198", source="MONDO:equivalentTo"}
`SCTID:44359008` should be the `MONDO:preferredExternal`.

2024-07-23 03:36 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +xref: SCTID:26745009 {source="https://orcid.org/0009-0002-1597-2198", source="MONDO:equivalentTo"}
`SCTID:26745009` should be the `MONDO:preferredExternal`

2024-07-23 04:20 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +xref: SCTID:73123008 {source="https://orcid.org/0009-0002-1597-2198"}
Change back to `source="MONDO:equivalentTo"`

2024-07-23 04:22 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +xref: SCTID:238031009 {source="https://orcid.org/0009-0002-1597-2198"}
Change back to `source="MONDO:equivalentTo"`

2024-07-23 15:11 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +xref: SCTID:26745009 {source="https://orcid.org/0009-0002-1597-2198", source="MONDO:equivalentTo"}
fixed

2024-07-23 15:14 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +xref: SCTID:238031009 {source="https://orcid.org/0009-0002-1597-2198"}
fixed

2024-07-23 15:14 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +xref: SCTID:44359008 {source="https://orcid.org/0009-0002-1597-2198", source="MONDO:equivalentTo"}
fixed

2024-07-23 17:47 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +xref: SCTID:238031009 {source="https://orcid.org/0009-0002-1597-2198"}
Actually `source="MONDO:equivalentTo"` needs to be removed to fix the proxy merge issue.

2024-07-23 18:13 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +xref: SCTID:73123008 {source="https://orcid.org/0009-0002-1597-2198"}
this needs to be reverted to fix the proxy merge issue and add curator Orcid, https://orcid.org/0009-0002-1597-2198

2024-07-24 00:03 UTC, twhetzel commented
I need information from the curator on two remaining xrefs in order to know which to add `MONDO:preferredExternal`

2024-07-29 20:46 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +xref: SCTID:238031009 {source="https://orcid.org/0009-0002-1597-2198"}
Sabrina says it's fine to remove this xref.

2024-07-29 20:46 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +xref: SCTID:44359008 {source="https://orcid.org/0009-0002-1597-2198", source="MONDO:equivalentTo", source="MONDO:preferredExternal"}
remove this `source="MONDO:preferredExternal"`

2024-07-29 20:47 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +xref: SCTID:73123008 {source="https://orcid.org/0009-0002-1597-2198"}
Remove this xref per Sabrina

2024-07-29 20:47 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +xref: SCTID:26745009 {source="https://orcid.org/0009-0002-1597-2198", source="MONDO:equivalentTo", source="MONDO:preferredExternal"}
remove `source="MONDO:preferredExternal"`

2024-07-31 15:01 UTC, sabrinatoro requested changes
@twhetzel There are many instances where there are 2 SCIT MONDO:equivalentTo. Even though there is no QC checks that will fail, we should add MONDO:preferredExternal to one of them, especially since we can see in this review that there are 2 SCIT MONDO:equivalentTo for the same term. 

Also, there a few duplicated lines which should be solved with running a normalization step.

2024-07-31 18:03 UTC, twhetzel commented on src/ontology/mondo-edit.obo
>  xref: UMLS:C0154861 {source="MONDO:equivalentTo", source="MONDO:MEDGEN", source="MEDGEN:1843490"}
You said Monday to only add "MONDO:preferredExternal" if known.

2024-07-31 18:27 UTC, sabrinatoro commented on src/ontology/mondo-edit.obo
>  xref: UMLS:C0154861 {source="MONDO:equivalentTo", source="MONDO:MEDGEN", source="MEDGEN:1843490"}
I said that we should have a "MONDO:preferredExternal", but we don't always know which one it is.
You/We, curators, need to look at these entries and decide which one, in our opinion, should be the preferred one.

2024-07-31 20:13 UTC, twhetzel commented on src/ontology/mondo-edit.obo
>  xref: UMLS:C0154861 {source="MONDO:equivalentTo", source="MONDO:MEDGEN", source="MEDGEN:1843490"}
Fixed.

2024-07-31 20:26 UTC, twhetzel commented on src/ontology/mondo-edit.obo
>  xref: UMLS:C0154251 {source="MONDO:equivalentTo", source="MONDO:MEDGEN", source="MEDGEN:57587"}
fixed

2024-07-31 22:10 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +xref: SCTID:28821000119102 {source="https://orcid.org/0009-0002-1597-2198", source="MONDO:equivalentTo"}
Checking with data submitter since SCTID:28821000119102 is not a valid SNOMED ID.

2024-08-01 17:03 UTC, blakebyer commented
| MONDO         | Match in MONDO (Existing xref) | Add to MONDO (PreferredExternal) |
|---------------|-----------------------|----------------------------------|
| MONDO:0001083 | SCTID:40488004        | SCTID:236466005                  |
| MONDO:0002525 | SCTID:267431006       | SCTID:402788005                  |
| MONDO:0002561 | SCTID:23585005        | SCTID:28821000119102             |
| MONDO:0009499 | SCTID:189979005       | SCTID:192782005                  |
| MONDO:0009590 | SCTID:68390005        | SCTID:297278001                  |
| MONDO:0009590 | SCTID:68390005        | SCTID:1003375005                 |
| MONDO:0009591 | SCTID:238031009       | SCTID:44359008                   |
| MONDO:0009653 | SCTID:111384001       | SCTID:725296006                  |
| MONDO:0009661 | SCTID:69463008        | SCTID:52677002                   |
| MONDO:0009757 | SCTID:18927009        | SCTID:67855008                   |
| MONDO:0010100 | SCTID:111385000       | SCTID:49562005                   |
| MONDO:0011759 | SCTID:73123008        | SCTID:26745009                   |
| MONDO:0018149 | SCTID:124465002       | SCTID:238025006                  |
| MONDO:0018868 | SCTID:66521008        | SCTID:238031009                  |
| MONDO:0018868 | SCTID:66521008        | SCTID:396338004                  |
| MONDO:0019148 | SCTID:82500001        | SCTID:238074007                  |
| MONDO:0019346 | SCTID:34960006        | SCTID:723675006                  |
| MONDO:0800088 | SCTID:254069004       | SCTID:279081001                  |

2024-08-01 17:05 UTC, blakebyer commented
Hi all, above is the table for where there are two equivalent SCTID xrefs. The left column is the MONDO ID, the middle column is the existing xref, and the right column is the preferred xref. Let me know if there are any other QC issues I can help with.

2024-08-01 17:09 UTC, blakebyer commented
There was a previous problem with the following. This SCTID is in the SNOMED CT browser but not in bioportal.
| MONDO | Match in MONDO (Existing xref) | Add to MONDO (PreferredExternal)
| -----------| ------------------------------------ | -------------------------------------- | 
| MONDO:0002561 | SCTID:23585005 | SCTID:28821000119102 | 

If this continues to cause problems, I recommend just using the existing xref.

2024-08-01 17:23 UTC, blakebyer commented
> MONDO	Match in MONDO (Existing xref)	Add to MONDO (PreferredExternal)
> MONDO:0001083	SCTID:40488004	SCTID:236466005
> MONDO:0002525	SCTID:267431006	SCTID:402788005
> MONDO:0002561	SCTID:23585005	SCTID:28821000119102
> MONDO:0009499	SCTID:189979005	SCTID:192782005
> **MONDO:0009590	SCTID:68390005	SCTID:297278001
> MONDO:0009590	SCTID:68390005	SCTID:1003375005**
> MONDO:0009591	SCTID:238031009	SCTID:44359008
> MONDO:0009653	SCTID:111384001	SCTID:725296006
> MONDO:0009661	SCTID:69463008	SCTID:52677002
> MONDO:0009757	SCTID:18927009	SCTID:67855008
> MONDO:0010100	SCTID:111385000	SCTID:49562005
> MONDO:0011759	SCTID:73123008	SCTID:26745009
> MONDO:0018149	SCTID:124465002	SCTID:238025006
> MONDO:0018868	SCTID:66521008	SCTID:238031009
> MONDO:0018868	SCTID:66521008	SCTID:396338004
> MONDO:0019148	SCTID:82500001	SCTID:238074007
> MONDO:0019346	SCTID:34960006	SCTID:723675006
> MONDO:0800088	SCTID:254069004	SCTID:279081001

Ignore these bolded lines, they were removed from the ROBOT template due to low confidence and 2 synonyms for one term.

2024-08-02 17:57 UTC, twhetzel commented
@blakebyer which should be the prefExt here for `MONDO:0018868`:

MONDO:0018868 | SCTID:66521008 | SCTID:238031009
-- | -- | --
MONDO:0018868 | SCTID:66521008 | SCTID:396338004

2024-08-02 18:09 UTC, blakebyer commented
@twhetzel MONDO:0018869 | SCTID:396338004

2024-08-02 18:15 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +xref: SCTID:28821000119102 {source="https://orcid.org/0009-0002-1597-2198", source="MONDO:equivalentTo"}
fixed

2024-08-02 18:15 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +xref: SCTID:192782005 {source="https://orcid.org/0009-0002-1597-2198", source="MONDO:equivalentTo"}
fixed

2024-08-02 18:17 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +xref: SCTID:297278001 {source="https://orcid.org/0009-0002-1597-2198", source="MONDO:equivalentTo"}
@blakebyer we missed this one

2024-08-02 18:17 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +xref: SCTID:725296006 {source="https://orcid.org/0009-0002-1597-2198", source="MONDO:equivalentTo"}
fixed

2024-08-02 18:17 UTC, twhetzel commented on src/ontology/mondo-edit.obo
>  xref: SCTID:69463008 {source="DOID:12800", source="MONDO:equivalentTo"}
fixed

2024-08-02 18:18 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +xref: SCTID:67855008 {source="https://orcid.org/0009-0002-1597-2198", source="MONDO:equivalentTo"}
fixed

2024-08-02 18:18 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +xref: SCTID:49562005 {source="https://orcid.org/0009-0002-1597-2198", source="MONDO:equivalentTo"}
fixed

2024-08-02 18:18 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +xref: SCTID:238025006 {source="https://orcid.org/0009-0002-1597-2198", source="MONDO:equivalentTo"}
fixed

2024-08-02 18:21 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +xref: SCTID:297278001 {source="https://orcid.org/0009-0002-1597-2198", source="MONDO:equivalentTo"}
preferred Ext is SCTID:44359008

2024-08-02 18:22 UTC, blakebyer commented
MONDO:0009591 | SCTID:238031009 |  SCTID:44359008

2024-08-02 18:32 UTC, blakebyer commented
Okay the preferred xref for MONDO:0009590 is SCTID:1003375005

2024-08-02 18:42 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +xref: SCTID:297278001 {source="https://orcid.org/0009-0002-1597-2198", source="MONDO:equivalentTo"}
[From Blake](https://github.com/monarch-initiative/mondo/pull/7950#issuecomment-2265931941): Okay the preferred xref for MONDO:0009590 is SCTID:1003375005

2024-08-02 18:42 UTC, twhetzel commented on src/ontology/mondo-edit.obo
> +xref: SCTID:297278001 {source="https://orcid.org/0009-0002-1597-2198", source="MONDO:equivalentTo"}
fixed

2024-08-02 18:46 UTC, blakebyer commented on src/ontology/mondo-edit.obo
>  xref: SCTID:238074007 {source="MONDO:possiblyEquivalent", source="DOID:14497"}
Should be source="MONDO:equivalentTo"

2024-08-02 20:21 UTC, sabrinatoro approved these changes
Everything looks good. 
Thank you @twhetzel and @blakebyer

2024-08-02 20:21 UTC, merged