add goals to generate a mapping change diff report
monarch-initiative/mondo pull request #7962
Opened 2024-07-14 15:03 UTC by twhetzel

addresses https://github.com/monarch-initiative/mondo/issues/7230

2024-07-18 10:20 UTC, matentzn requested changes
1 important, 1 minor suggestion

2024-07-18 10:20 UTC, matentzn commented on src/ontology/mondo.Makefile
> +tmp/mondo-released.obo:
```suggestion
tmp/mondo-released.obo: .FORCE
```

I know this is a last resort dependency but we should consider it as this code should always be re-run when the diff is rerun. The SOP takes care of it as well, as it instructs the use of -B, but this is just safer

2024-07-18 10:20 UTC, matentzn commented on src/ontology/mondo.Makefile
> +	wget http://purl.obolibrary.org/obo/mondo.obo -O tmp/mondo-released.obo
```suggestion
	wget http://purl.obolibrary.org/obo/mondo/$(KGCL_ONTOLOGY) -O $@
```

So we compare the same things.

2024-07-18 10:24 UTC, matentzn requested changes
Another thing I just saw

2024-07-18 10:24 UTC, matentzn commented on src/ontology/mondo.Makefile
> +prepare_release: kgcl-diff
```suggestion
all: kgcl-diff
```

2024-07-19 16:45 UTC, matentzn approved these changes
LGTM, assuming you tried this!

2024-07-19 16:51 UTC, twhetzel commented
No, actually I have not but I will.

2024-07-23 02:00 UTC, twhetzel commented on src/ontology/mondo.Makefile
> +reports/difference_release_base.txt: tmp/mondo-released.obo $(KGCL_ONTOLOGY)
@matentzn how does this get run?

2024-07-23 04:44 UTC, twhetzel reviewed
If I run `sh run.sh make kgcl-diff -B` I get:
```
...
runoak -i simpleobo:tmp/mondo-released.obo diff -X simpleobo:mondo-base.obo -o reports/difference_release_base.yaml --output-type yaml
runoak -i simpleobo:tmp/mondo-released.obo diff -X simpleobo:mondo-base.obo \
-o reports/difference_release_base.tsv --output-type csv --statistics --group-by-property oio:hasOBONamespace
runoak -i simpleobo:tmp/mondo-released.obo diff -X simpleobo:mondo-base.obo -o reports/difference_release_base.md --output-type md
No handler for key: RemoveNodeFromSubset
```

When I tried: `sh run.sh make all -B` I ran into this error:
```
MISSING FILE ERROR file '../sparql/preprocess-module.ru' does not exist
```


It runs in "obolibrary/odkfull:latest" and I pulled the latest.

Edit: Each `make` command above resulted in failure with the error messages as posted above.

2024-07-23 09:46 UTC, matentzn commented on src/ontology/mondo.Makefile
> +reports/difference_release_base.txt: tmp/mondo-released.obo $(KGCL_ONTOLOGY)
Its not, I removed it!

2024-07-23 09:50 UTC, matentzn commented
> No handler for key: RemoveNodeFromSubset

@hrshdhgd?

> MISSING FILE ERROR file '../sparql/preprocess-module.ru' does not exist

I will track that down for the sake of identifying the leak, but in general we should never run:

```
sh run.sh make all -B
```

Always run:

```
sh run.sh make all -B IMP=false
```

Somewhere in the main pipeline there is an import dependency that should not exist anymore, but this is unrelated to this PR.

2024-07-23 16:08 UTC, hrshdhgd commented
> > No handler for key: RemoveNodeFromSubset
> 
> @hrshdhgd?

Sorry about that. Somehow this got missed in `oaklib`. Working a PR right now.

2024-07-23 16:35 UTC, twhetzel commented
I ran `sh run.sh make all -B IMP=false` and the release process finished successfully. 

I then checked `reports/difference_release_base.md` against the most recent [Orphanet alignment for August release](https://github.com/monarch-initiative/mondo/pull/7933) and [OMIM Alignment for August release](https://github.com/monarch-initiative/mondo/pull/7932) and the new xrefs added into Mondo are found in the new report, e.g. `reports/difference_release_base.md`.

2024-07-23 16:36 UTC, twhetzel commented
@matentzn anything else that should be checked or done before merging?

2024-07-23 17:22 UTC, matentzn commented
No, good to go!

2024-07-23 20:26 UTC, hrshdhgd commented
> > > No handler for key: RemoveNodeFromSubset
> > 
> > 
> > @hrshdhgd?
> 
> Sorry about that. Somehow this got missed in `oaklib`. Working on a [PR](https://github.com/INCATools/ontology-access-kit/pull/783) right now.

`oaklib` v0.6.12 should take care of this

2024-07-23 21:14 UTC, matentzn commented
Thank you @hrshdhgd

It will be a while before we will notice this change, we just updated ODK and it will be at least until October now :P thanks for fixing! @twhetzel i think we can merge this!

2024-07-25 06:00 UTC, merged