add synonyms to MONDO:0016089 'infantile Krabbe disease'
monarch-initiative/mondo pull request #8110
Opened 2024-08-26 13:06 UTC by ehurwitz

close #8029

2024-08-26 15:53 UTC, ehurwitz commented
@sabrinatoro This is a PR adding the 3 exact synonyms (early onset Krabbe disease, early-onset Krabbe disease, early symptomatic Krabbe disease) for infantile Krabbe disease MONDO:0016089 requested.

2024-08-26 17:52 UTC, sabrinatoro requested changes
@ehurwitz Thank you for your PR. I am requesting some changes. Please let me know if you have questions. 
After you have addressed these changes, please assign back to me. Thank you.

2024-08-26 17:52 UTC, sabrinatoro commented on src/ontology/mondo-edit.obo
> +synonym: "early onset Krabbe disease" EXACT []
Please add a "database cross-reference" annotation to notify where this synonym comes from (ie where is this name used). 
This database x-ref can be a PMID, another x-ref (eg Orphanet:206436), and/or an orcid)

2024-08-26 17:52 UTC, sabrinatoro commented on src/ontology/mondo-edit.obo
> +synonym: "early symptomatic Krabbe" EXACT []
Please add a "database cross-reference" annotation to notify where this synonym comes from (ie where is this name used). 
This database x-ref can be a PMID, another x-ref (eg Orphanet:206436), and/or an orcid)

2024-08-26 17:52 UTC, sabrinatoro commented on src/ontology/mondo-edit.obo
> +synonym: "early-onset Krabbe disease" EXACT []
Please add a "database cross-reference" annotation to notify where this synonym comes from (ie where is this name used). 
This database x-ref can be a PMID, another x-ref (eg Orphanet:206436), and/or an orcid)

2024-08-27 13:04 UTC, ehurwitz commented
@sabrinatoro database cross-reference annotations (PMIDs) have been been added for each of the 3 synonyms. Please let me know if there are any other issues!

2024-09-18 18:08 UTC, sabrinatoro approved these changes

2024-09-18 18:08 UTC, merged